# Generated by Django 3.1.14 on 2022-05-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendpg', '0003_tracks_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
